### ISSUE TITLE
Exclude directories

### ISSUE THREAD

**Issue by Wikunia** [wakatime/brackets-wakatime#1]
I would like to exclude some working directories.
For example: C:/..../foobar/ shouldn't be logged!

**Comment by drm-code** [comment]
Hi, is there any way to include only specific directories? I mean I don't really want to wakatime logged all my work, only on a certains directories, does it exist an include option? or wakatime register the hole system?

**Comment by alanhamlett** [comment]
@drm-code add this regex to your `exclude config key:

`exclude = .*`

Then add regexes to match each folder you DO want to log:

```
include = 
    \/path\/to\/project1
    \/path\/to\/project2
```

That goes in your `~/.wakatime.cfg` file. More info here:
https://github.com/wakatime/wakatime#configuring

**Comment by drm-code** [comment]
Yes that works exactly as I expect, thanks :)

**Comment by namdnguyen** [comment]
Hi, I'm having some trouble setting directories to be excluded in my `.wakatime.cfg` file. I'm doing something like the following, but it doesn't seem to ignore activity in that directory or its subdirectories:
```
exclude =
    ^/home/nam/Downloads/.*
```

Am I doing something incorrectly? I noticed that you escaped the path slashes in your "include" example. Do I need to do that, too? Is the `.*` also necessary for my exclude rule? Thanks!

**Comment by alanhamlett** [comment]
That regex is correct, but Brackets is the one plugin that doesn't use the ~/.wakatime.cfg file so it's not using the exclude rule.

**Comment by namdnguyen** [comment]
My mistake. I didn't notice which repo I was in. I was actually having the issue with the cfg file and the emacs plugin. Should I recreate the issue over there?

**Comment by alanhamlett** [comment]
You can create it here:
https://github.com/wakatime/wakatime/issues/new

Also, add this line to your `.wakatime.cfg` and check your `~/.wakatime.log` file for any related logging:
`debug=true`

**Comment by marcus-hiles** [comment]
@alanhamlett this was helpful, thanks

**Comment by marcus-hiles** [comment]
@namdnguyen have you been able to create an issue on this in the wakatime repo? Kindly share the link to it, thanks.
